# Generated by Django 2.1.4 on 2020-06-07 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_uploadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='token',
            field=models.UUIDField(default=uuid.UUID('ac06fa6b-27c6-40a3-860e-6afbcc9f5a48')),
        ),
    ]
