# Generated by Django 2.1.4 on 2020-06-11 20:34

import accounts.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_uploadmodel_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.handle_cv_upload),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.handle_prof_img_upload),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='image',
            field=models.ImageField(upload_to=accounts.models.handle_tmp_ad_img_upload),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='token',
            field=models.UUIDField(default=uuid.UUID('dcd33951-58ca-4069-acab-64c85be79215'), primary_key=True, serialize=False),
        ),
    ]
