# Generated by Django 2.1.4 on 2020-06-17 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200612_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
