# Generated by Django 2.1.4 on 2020-02-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebridge', '0002_category_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product-images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='prof-images/'),
        ),
    ]
