# Generated by Django 2.1.4 on 2020-05-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebridge', '0013_auto_20200521_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='zip_code',
        ),
    ]
