# Generated by Django 2.1.4 on 2020-05-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebridge', '0015_profile_is_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
