# Generated by Django 2.1.4 on 2020-05-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebridge', '0018_auto_20200522_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ebridge.ProductDescription'),
        ),
    ]
