# Generated by Django 2.1.4 on 2020-05-22 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebridge', '0019_auto_20200522_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
