# Generated by Django 2.1.4 on 2020-05-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebridge', '0022_auto_20200522_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
