# Generated by Django 2.1.4 on 2020-05-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebridge', '0023_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='ebridge.ProductDescription'),
        ),
    ]
