# Generated by Django 2.1.4 on 2020-05-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebridge', '0024_auto_20200524_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collaborators',
            field=models.ManyToManyField(to='ebridge.Collaboration'),
        ),
    ]
