# Generated by Django 2.1.4 on 2020-12-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebridge', '0028_auto_20200531_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['count'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content-images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='ProductDescription',
        ),
        migrations.AddField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(to='ebridge.Product'),
        ),
    ]
