# Generated by Django 2.1.4 on 2020-12-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebridge', '0030_auto_20201216_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['use_count']},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='count',
            new_name='use_count',
        ),
    ]
