# Generated by Django 2.1.4 on 2021-01-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebridge', '0031_auto_20201216_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
