# Generated by Django 2.1.4 on 2021-01-02 06:07

from django.db import migrations, models
import ebridge.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebridge', '0032_auto_20210101_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ebridge.models.product_file_directory_path),
        ),
    ]
